export const NUMBERS = [
  'cero',
  'uno',
  'dos',
  'tres',
  'cuatro',
  'cinco',
  'seis',
  'siete',
  'ocho',
  'nueve',
  'diez',
  'once',
  'doce',
  'trece',
  'catorce',
  'quince',
  'dieciséis',
  'diecisiete',
  'dieciocho',
  'diecinueve',
  'veinte',
  'veintiuno',
  'veintidós',
  'veintitrés',
  'veinticuatro',
  'veinticinco',
  'veintiséis',
  'veintisiete',
  'veintiocho',
  'veintinueve',
  'treinta',
  'treinta y uno',
  'treinta y dos',
  'treinta y tres',
  'treinta y cuatro',
  'treinta y cinco',
  'treinta y seis',
  'treinta y siete',
  'treinta y ocho',
  'treinta y nueve',
  'cuarenta',
  'cuarenta y uno',
  'cuarenta y dos',
  'cuarenta y tres',
  'cuarenta y cuatro',
  'cuarenta y cinco',
  'cuarenta y seis',
  'cuarenta y siete',
  'cuarenta y ocho',
  'cuarenta y nueve',
  'cincuenta',
  'cincuenta y uno',
  'cincuenta y dos',
  'cincuenta y tres',
  'cincuenta y cuatro',
  'cincuenta y cinco',
  'cincuenta y seis',
  'cincuenta y siete',
  'cincuenta y ocho',
  'cincuenta y nueve',
];